"""DermLIP skin condition labels and prompt template."""

SKIN_CONDITIONS = [
    "acne vulgaris",
    "actinic keratosis",
    "alopecia areata",
    "atopic dermatitis",
    "basal cell carcinoma",
    "bullous pemphigoid",
    "cellulitis",
    "contact dermatitis",
    "dermatofibroma",
    "eczema",
    "folliculitis",
    "fungal infection",
    "granuloma annulare",
    "hemangioma",
    "herpes simplex",
    "herpes zoster",
    "hives",
    "impetigo",
    "keloid",
    "lichen planus",
    "lupus erythematosus",
    "melanoma",
    "melasma",
    "molluscum contagiosum",
    "nevus",
    "onychomycosis",
    "perioral dermatitis",
    "pityriasis rosea",
    "psoriasis",
    "rosacea",
    "scabies",
    "scleroderma",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "squamous cell carcinoma",
    "tinea corporis",
    "tinea versicolor",
    "urticaria",
    "vitiligo",
    "warts",
]

PROMPT_TEMPLATE = "This is a skin image of {condition}"
